apiVersion: apps/v1
kind: Deployment
metadata:
  name: details-deploy
  namespace: cdps-19
spec:
  replicas: 4
  selector:
    matchLabels:
      app: details
  template:
    metadata:
      labels:
        app: details
    spec:
      containers:
      - name: details
        image: cdps-details:g19
        ports:
        - containerPort: 7070
