apiVersion: v1
kind: Service
metadata:
  name: details-svc
  namespace: cdps-19
spec:
  selector:
    app: details
  ports:
  - port: 9080
    targetPort: 7070
---
apiVersion: v1
kind: Service
metadata:
  name: ratings-svc
  namespace: cdps-19
spec:
  selector:
    app: ratings
  ports:
  - port: 9080
    targetPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: reviews-svc
  namespace: cdps-19
spec:
  selector:
    app: reviews
  ports:
  - port: 9080
    targetPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: productpage-lb
  namespace: cdps-19
spec:
  type: LoadBalancer
  selector:
    app: productpage
  ports:
  - port: 80
    targetPort: 9080
